name: publish-comments

on:
  issue_comment:
    types: [created, edited]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Turn comment into file
        run: |
          ID=${{ github.event.comment.id }}
          AUTHOR=${{ github.event.comment.user.login }}
          DATE=${{ github.event.comment.created_at }}
          COMMENT=$(echo "${{ github.event.comment.body }}")
          NO_TAGS=${COMMENT//[<>]/\`}
          FOLDER=src/comments

          printf '%b\n' "\r\n<div class=\"comment\"><p>${AUTHOR} says:</p><p>${NO_TAGS//$'\n'/\<\/p\>\<p\>}</p><p>${DATE}</p></div>\r\n" > ${FOLDER}/${ID}.html
      - name: Assemble page
        run: |
          cat src/header.html > docs/index.html
          find src/comments/ -name "*.html" | sort -r | xargs -I % cat % >> docs/index.html
          cat src/footer.html >> docs/index.html
      - name: Push changes to repo
        run: |
          REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config user.email "hello@victoria.dev"
          git config user.name "${{ github.actor }}"

          git pull ${REMOTE}
          git checkout master
          git add .
          git status
          git commit -am "Add new comment"
          git push ${REMOTE} master
